# Project information
site_name: Atas das Reuniões do Comitê Científico do MONAN 
site_author: Carlos Frederico Bastarz
site_description: Site com as Atas das Reuniões do Comitê Científico do MONAN

# Repository
repo_name: monanadmin/monan_cc_docs
repo_url: https://github.com/monanadmin/monan_cc_docs
edit_uri: edit/master/docs/

# Page tree
nav:
  - Atas 2021:
    - '05 de Maio de 2021': ata_cc_05_maio_2021.md
    - '04 de Junho de 20201': ata_cc_04_junho_2021.md
    - '30 de Agosto de 2021': ata_cc_30_agosto_2021.md
    - '04 de Novembro de 2021': ata_cc_04_novembro_2021.md
    - '06 de Dezembro de 2021': ata_cc_06_dezembro_2021.md
#  - Atas 2022:
#    - '28 de Março de 2022': ata_cc_28_marco_2022.md
  - Seminários:
    - 'ATOS-BULL': seminarios_atos_bull.md
    - 'NVIDIA': seminarios_nvidia.md
  - Arquivos:
    - 'Carta de Apresentação do MONAN': carta_apres_monan.md
    - 'Outros Arquivos': outros_arquivos.md

# Configuration
theme: 
  name: material
  language: pt-BR

# PDF page style
#extra_css:
#  - css/pdfstyle.css

# Extensions
markdown_extensions:
  - footnotes
  - tables
  - admonition
  - abbr
  - pymdownx.snippets
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.tabbed:
      alternate_style: true

# Plugins
plugins:
  - mkdocs-video
  - search
#  - pdf-export
#  - mkpdfs
